/*   
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewAndController;

//import java.awt.List;
import ConnectDatabase.ConnectToXampp;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modun.banyanFlower;
import modun.listSaveInput;
import modun.singleFlower;

public class ViewAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ViewAddmin
     */
    private final List<singleFlower> listsinger = new ArrayList<>();
    private final List<banyanFlower> listbanyan = new ArrayList<>(); 
    private final List<listSaveInput>  listSaveOut = new ArrayList<>();
    private List<listSaveInput>  listSave = new ArrayList<>();
    private ViewInputList vInputList;
    private ViewOutputList vOutputList;
    private String typeFlower;
    private String typeFlowerKK;
    
    public ViewAdmin() {
        initComponents();
        uploadDataBase();
        viewimport.setVisible(false);
        viewexport.setVisible(false);
        viewtable.setVisible(false);
        
    }
    /**
     *
     * @return 
     */
    
    private void uploadDataBase(){
        listSave = ConnectToXampp.findAll();
//        System.out.println("Ok");
        listSave.forEach((listSaveInput e) -> {
            if((e.getType()).equals("Hoa đơn")){
                listsinger.add(new singleFlower(e.getpetalsFlowerNum(), e.getName(), e.getCode(), e.getType(), e.getAmount(), e.getColor()));
            }else if((e.getType()).equals("Hoa đa")){
                listbanyan.add(new banyanFlower(e.getsubFlowerNum(), e.getName(), e.getCode(), e.getType(), e.getAmount(), e.getColor()));
            }
        });
        createTable(listsinger, listbanyan);
    }
    
    private void createTable(List<singleFlower> listFl, List<banyanFlower> listfl){
        
        Collections.sort(listfl, (banyanFlower o1, banyanFlower o2) -> {
            return o1.getCode().compareTo(o2.getCode());
        });
        Collections.sort(listFl, (singleFlower o1, singleFlower o2) -> {
            return o1.getCode().compareTo(o2.getCode());
        });
        DefaultTableModel table = new DefaultTableModel();
        listFlowerTable.setModel(table);
        table.addColumn("Mã hoa");
        table.addColumn("Tên hoa");
        table.addColumn("Loại hoa");
        table.addColumn("Màu sắc");
        table.addColumn("Số lượng");
        table.addColumn("Số hoa con");
        table.addColumn("Số cánh hoa");
        for(singleFlower flower : listFl){
            table.addRow(new Object[] {flower.getCode(), flower.getName(), flower.getType(), flower.getColor(), flower.getAmount(), 0, flower.getPetalsFlowerNum()});
        }
        for(banyanFlower flower : listfl){
            table.addRow(new Object[] {flower.getCode(), flower.getName(), flower.getType(), flower.getColor(), flower.getAmount(), flower.getSubFlowerNum(), 0});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        viewimport = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Codetxt = new javax.swing.JTextField();
        Nametxt = new javax.swing.JTextField();
        Colortxt = new javax.swing.JTextField();
        typeFlower1 = new javax.swing.JRadioButton();
        typeFlower2 = new javax.swing.JRadioButton();
        Amounttxt = new javax.swing.JTextField();
        subFlowerNumtxt = new javax.swing.JTextField();
        petalsFlowerNumtxt = new javax.swing.JTextField();
        cinBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        viewexport = new javax.swing.JPanel();
        OrderOuttxt = new javax.swing.JTextField();
        jlable = new javax.swing.JLabel();
        coutBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        viewtable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFlowerTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 102));
        jLabel11.setText("Quản Lý Hoa Khô");

        jPanel12.setBackground(new java.awt.Color(0, 102, 0));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewAndController/icon2.png"))); // NOI18N
        jLabel12.setText("Nhập Hoa Khô");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(204, 0, 51));
        jPanel10.setPreferredSize(new java.awt.Dimension(75, 3));

        jPanel11.setBackground(new java.awt.Color(204, 0, 51));
        jPanel11.setPreferredSize(new java.awt.Dimension(75, 3));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(204, 0, 51));
        jPanel13.setPreferredSize(new java.awt.Dimension(75, 3));

        jPanel14.setBackground(new java.awt.Color(204, 0, 51));
        jPanel14.setPreferredSize(new java.awt.Dimension(75, 3));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 102));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewAndController/icon1.png"))); // NOI18N
        jLabel13.setText("Xuất Hoa khô");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Phiếu Nhập");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 102));
        jLabel10.setText("Phiếu Xuất");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(153, 255, 255));
        jPanel15.setPreferredSize(new java.awt.Dimension(75, 3));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel17.setBackground(new java.awt.Color(0, 102, 255));
        jPanel17.setPreferredSize(new java.awt.Dimension(75, 3));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel18.setBackground(new java.awt.Color(153, 255, 255));
        jPanel18.setPreferredSize(new java.awt.Dimension(75, 3));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap(11, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(40, 40, 40))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addContainerGap(1112, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        viewimport.setBackground(new java.awt.Color(0, 153, 0));

        jLabel3.setText("Mã Hoa");

        jLabel4.setText("Tên hoa");

        jLabel5.setText("Loại hoa");

        jLabel6.setText("Màu sắc");

        jLabel7.setText("Số lượng");

        jLabel8.setText("Số hoa con");

        jLabel9.setText("Số cánh hoa");

        Codetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodetxtActionPerformed(evt);
            }
        });

        buttonGroup1.add(typeFlower1);
        typeFlower1.setText("Hoa đa");
        typeFlower1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFlower1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(typeFlower2);
        typeFlower2.setText("Hoa đơn");
        typeFlower2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFlower2ActionPerformed(evt);
            }
        });

        petalsFlowerNumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petalsFlowerNumtxtActionPerformed(evt);
            }
        });

        cinBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cinBtn.setText("Nhập");
        cinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel16.setText("Nhập Hoa Khô");

        javax.swing.GroupLayout viewimportLayout = new javax.swing.GroupLayout(viewimport);
        viewimport.setLayout(viewimportLayout);
        viewimportLayout.setHorizontalGroup(
            viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewimportLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewimportLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(92, 92, 92)
                        .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subFlowerNumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Amounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(petalsFlowerNumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(viewimportLayout.createSequentialGroup()
                        .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewimportLayout.createSequentialGroup()
                        .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(viewimportLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(typeFlower1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(typeFlower2))
                            .addGroup(viewimportLayout.createSequentialGroup()
                                .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(viewimportLayout.createSequentialGroup()
                                        .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(viewimportLayout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(92, 92, 92)))
                                .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Colortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Codetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36))))
            .addGroup(viewimportLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewimportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cinBtn)
                .addGap(18, 18, 18)
                .addComponent(resetBtn)
                .addGap(105, 105, 105))
        );
        viewimportLayout.setVerticalGroup(
            viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewimportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(1, 1, 1)
                .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(typeFlower2)
                        .addComponent(typeFlower1))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Colortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subFlowerNumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petalsFlowerNumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewimportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn)
                    .addComponent(cinBtn))
                .addGap(17, 17, 17))
        );

        viewexport.setBackground(new java.awt.Color(0, 153, 0));

        jlable.setText("Số lượng xuất");

        coutBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        coutBtn.setText("Xuất ");
        coutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coutBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel14.setText("Xuất Hoa KHô");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Chọn Sản Phẩm Cần Xuất");

        javax.swing.GroupLayout viewexportLayout = new javax.swing.GroupLayout(viewexport);
        viewexport.setLayout(viewexportLayout);
        viewexportLayout.setHorizontalGroup(
            viewexportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewexportLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(OrderOuttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(viewexportLayout.createSequentialGroup()
                .addGroup(viewexportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewexportLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(coutBtn))
                    .addGroup(viewexportLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel14))
                    .addGroup(viewexportLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel15)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        viewexportLayout.setVerticalGroup(
            viewexportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewexportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(63, 63, 63)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(viewexportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderOuttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(coutBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        viewtable.setBackground(new java.awt.Color(0, 153, 0));

        listFlowerTable.setBackground(new java.awt.Color(0, 153, 0));
        listFlowerTable.setForeground(new java.awt.Color(255, 255, 51));
        listFlowerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hoa", "Tên hoa", "Loại hoa", "Màu sắc", "Số lượng", "Số hoa con", "Số cánh hoa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listFlowerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listFlowerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listFlowerTable);
        if (listFlowerTable.getColumnModel().getColumnCount() > 0) {
            listFlowerTable.getColumnModel().getColumn(0).setResizable(false);
            listFlowerTable.getColumnModel().getColumn(1).setResizable(false);
            listFlowerTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            listFlowerTable.getColumnModel().getColumn(2).setResizable(false);
            listFlowerTable.getColumnModel().getColumn(3).setResizable(false);
            listFlowerTable.getColumnModel().getColumn(4).setResizable(false);
            listFlowerTable.getColumnModel().getColumn(5).setResizable(false);
            listFlowerTable.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout viewtableLayout = new javax.swing.GroupLayout(viewtable);
        viewtable.setLayout(viewtableLayout);
        viewtableLayout.setHorizontalGroup(
            viewtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewtableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewtableLayout.setVerticalGroup(
            viewtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewtableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 255));
        jLabel17.setText("Chương Trình Quản Lý Hoa KHô");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(viewimport, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewexport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewtable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewimport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewexport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(258, 258, 258)
                .addComponent(jLabel17)
                .addContainerGap(499, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 605, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinBtnActionPerformed
        // TODO add your handling code here:
        Calendar Cal = Calendar.getInstance();
        int year = Cal.get(Calendar.YEAR);
        int month = Cal.get(Calendar.MONTH)+1;
        int day = Cal.get(Calendar.DAY_OF_MONTH);
        int hour = Cal.get(Calendar.HOUR_OF_DAY);
        int minute = Cal.get(Calendar.MINUTE);
        int second = Cal.get(Calendar.SECOND);
        
        String time = String.valueOf(second)+":"+String.valueOf(minute)+":"+String.valueOf(hour)+":"
                      +" "+String.valueOf(day)+"/"+String.valueOf(month)+"/"+String.valueOf(year);
        
        String code = Codetxt.getText();
        String name = Nametxt.getText();
        String type = typeFlower;
        String color = Colortxt.getText();
        String amount = Amounttxt.getText();
        String subFlower = subFlowerNumtxt.getText();
        String petalsFlower = petalsFlowerNumtxt.getText();
        double mark = 0;
        
        if(code.equals("")||name.equals("")||type.equals("")||color.equals("")||subFlower.equals("")||petalsFlower.equals("")||amount.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Hãy điền đủ thông tin!");
            return;
        }
        if(Double.parseDouble(amount) <= 0){
            JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số dương!");
            return;
        }
        
            listSave.add(new listSaveInput(code, name, type, color, Double.parseDouble(amount), Double.parseDouble(subFlower), Double.parseDouble(petalsFlower), time));
        
        if(type.equals("Hoa đơn")){
            for(singleFlower flower : listsinger){
                if(code.equals(flower.getCode())){
                    flower.setAmount(Double.parseDouble(amount) + flower.getAmount());
                    createTable(listsinger, listbanyan);
                    mark = 1;
                }
            }
            if(mark == 0){
                listsinger.add(new singleFlower(Double.parseDouble(petalsFlower), name, code, type, Double.parseDouble(amount), color));
                createTable(listsinger, listbanyan);
            }
        }else{
            for(banyanFlower flower : listbanyan){
                if(code.equals(flower.getCode())){
                    flower.setAmount(Double.parseDouble(amount) + flower.getAmount());
                    createTable(listsinger, listbanyan);
                    mark = 1;
                }
            }
            if(mark == 0){
                listbanyan.add(new banyanFlower(Double.parseDouble(subFlower), name, code, type, Double.parseDouble(amount), color));
                createTable(listsinger, listbanyan);
            }
            
        }
    }//GEN-LAST:event_cinBtnActionPerformed

    private void typeFlower1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFlower1ActionPerformed
        // TODO add your handling code here:
        typeFlower = "Hoa đa";
        petalsFlowerNumtxt.setText("0");
        subFlowerNumtxt.setText("");
    }//GEN-LAST:event_typeFlower1ActionPerformed

    private void typeFlower2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFlower2ActionPerformed
        // TODO add your handling code here:
        typeFlower = "Hoa đơn";
        petalsFlowerNumtxt.setText("");
        subFlowerNumtxt.setText("0");
    }//GEN-LAST:event_typeFlower2ActionPerformed
    private void setInform(String code, String name, String type, String color, double amount, String subFlower, String petalsFlower){
        Codetxt.setText(code);
        Nametxt.setText(name);
        if(type.equals("Hoa đa")){
            typeFlower1.setSelected(true);
        }else{
            typeFlower2.setSelected(true);
        }
        Colortxt.setText(color);
        Amounttxt.setText(String.valueOf(amount));
        subFlowerNumtxt.setText(subFlower);
        petalsFlowerNumtxt.setText(petalsFlower);
    }
    private void listFlowerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFlowerTableMouseClicked
        // TODO add your handling code here:
        int selectRow = listFlowerTable.getSelectedRow();
        if(selectRow >= 0){
            String code = (String) listFlowerTable.getValueAt(selectRow, 0);
            String name = (String) listFlowerTable.getValueAt(selectRow, 1);
            String type = (String) listFlowerTable.getValueAt(selectRow, 2);
            typeFlower = type;
            String color = (String) listFlowerTable.getValueAt(selectRow, 3);
            double amount =  (double) listFlowerTable.getValueAt(selectRow, 4);
            String subFlower = (String) (listFlowerTable.getValueAt(selectRow, 5)+"");
            String petalsFlower = (String) (listFlowerTable.getValueAt(selectRow, 6)+"");
            setInform(code, name, type, color, amount, subFlower, petalsFlower);
        }
    }//GEN-LAST:event_listFlowerTableMouseClicked

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        Codetxt.setText("");
        Nametxt.setText("");
        buttonGroup1.clearSelection();
        Colortxt.setText( "");
        Amounttxt.setText(String.valueOf(""));
        subFlowerNumtxt.setText("");
        petalsFlowerNumtxt.setText("");
        OrderOuttxt.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void coutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coutBtnActionPerformed
        // TODO add your handling code here:
        Calendar Cal = Calendar.getInstance();
        int year = Cal.get(Calendar.YEAR);
        int month = Cal.get(Calendar.MONTH)+1;
        int day = Cal.get(Calendar.DAY_OF_MONTH);
        int hour = Cal.get(Calendar.HOUR_OF_DAY);
        int minute = Cal.get(Calendar.MINUTE);
        int second = Cal.get(Calendar.SECOND);

        String time = String.valueOf(second)+":"+String.valueOf(minute)+":"+String.valueOf(hour)+":"
        +" "+String.valueOf(day)+"/"+String.valueOf(month)+"/"+String.valueOf(year);

        if(typeFlower.equals("Hoa đơn")){
            for(singleFlower flower : listsinger){
                if(Codetxt.getText().equals(flower.getCode())){
                    if(Double.parseDouble(OrderOuttxt.getText()) <= flower.getAmount()){
                        listSaveOut.add(new listSaveInput(flower.getName(), flower.getCode(), flower.getType(), flower.getColor(), Double.parseDouble(OrderOuttxt.getText()), 0, flower.getPetalsFlowerNum(), time));
                        flower.setAmount(flower.getAmount() - Double.parseDouble(OrderOuttxt.getText()));
                        createTable(listsinger, listbanyan);
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Không đủ số lượng để xuất");
                    }
                }
            }
        }else{
            for(banyanFlower flower : listbanyan){
                if(Codetxt.getText().equals(flower.getCode())){
                    if(Double.parseDouble(OrderOuttxt.getText()) <= flower.getAmount()){
                        listSaveOut.add(new listSaveInput(flower.getName(), flower.getCode(), flower.getType(), flower.getColor(), Double.parseDouble(OrderOuttxt.getText()), flower.getSubFlowerNum(), 0, time));
                        flower.setAmount(flower.getAmount() - Double.parseDouble(OrderOuttxt.getText()));
                        createTable(listsinger, listbanyan);
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Không đủ số lượng để xuất");
                    }
                }
            }
        }
        int index = 0;
        for(singleFlower flower : listsinger){
            if(flower.getAmount() == 0){
                listsinger.remove(index);
                return;
            }
            index++;
        }
        int indexx = 0;
        for(banyanFlower flower : listbanyan){
            if(flower.getAmount() == 0){
                listbanyan.remove(indexx);
                return;
            } else {
            }
            indexx++;
        }
        createTable(listsinger, listbanyan);
    }//GEN-LAST:event_coutBtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       this.setVisible(false);
        vInputList = new ViewInputList(listSave, this);
        vInputList.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
            this.setVisible(false);
        vOutputList = new ViewOutputList(listSaveOut, this);
        vOutputList.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void petalsFlowerNumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petalsFlowerNumtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petalsFlowerNumtxtActionPerformed

    private void CodetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodetxtActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        viewimport.setVisible(true);
        viewexport.setVisible(false);
        viewtable.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        viewimport.setVisible(false);
        viewexport.setVisible(true);
        viewtable.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewAdmin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amounttxt;
    private javax.swing.JTextField Codetxt;
    private javax.swing.JTextField Colortxt;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JTextField OrderOuttxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cinBtn;
    private javax.swing.JButton coutBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlable;
    private javax.swing.JTable listFlowerTable;
    private javax.swing.JTextField petalsFlowerNumtxt;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField subFlowerNumtxt;
    private javax.swing.JRadioButton typeFlower1;
    private javax.swing.JRadioButton typeFlower2;
    private javax.swing.JPanel viewexport;
    private javax.swing.JPanel viewimport;
    private javax.swing.JPanel viewtable;
    // End of variables declaration//GEN-END:variables

    private void listFlowerTableMouseClicked(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
