/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewAndController;

import ConnectDatabase.ConnectToXampp;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modun.banyanFlower;
import modun.listSaveInput;
import modun.singleFlower;
import viewAndController.View_LSNhap;
import viewAndController.View_LSXuat;

public class View_KiemKe extends javax.swing.JFrame {

    /**
     * Creates new form ViewAddmin
     */
    private final List<singleFlower> listsinger = new ArrayList<>();
    private final List<banyanFlower> listbanyan = new ArrayList<>();
    private final List<listSaveInput> listSaveOut = new ArrayList<>();
    private List<listSaveInput> listSave = new ArrayList<>();
    private View_LSNhap vInputList;
    private View_LSXuat vOutputList;
    private String typeFlower;
    private String typeFlowerKK;
    private View_Admin vAdmin;

    public View_KiemKe() {
        initComponents();
        uploadDataBase();
    }

    /**
     *
     * @return
     */
    private void uploadDataBase() {
        listSave = ConnectToXampp.findAll();
        listSave.forEach((listSaveInput e) -> {
            if ((e.getType()).equals("Hoa đơn")) {
                listsinger.add(new singleFlower(e.getpetalsFlowerNum(), e.getName(), e.getCode(), e.getType(), e.getAmount(), e.getColor()));
            } else if ((e.getType()).equals("Hoa đa")) {
                listbanyan.add(new banyanFlower(e.getsubFlowerNum(), e.getName(), e.getCode(), e.getType(), e.getAmount(), e.getColor()));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        codeKKtxt = new javax.swing.JTextField();
        typeFlower1KKtxt = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        NameKKtxt = new javax.swing.JTextField();
        AmountKKtxt = new javax.swing.JTextField();
        typeFlower2KKtxt = new javax.swing.JRadioButton();
        ResultBtn = new javax.swing.JButton();
        resetKKBtn = new javax.swing.JButton();
        home = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Kiểm kê");

        jLabel13.setText("Mã hoa");

        jLabel14.setText("Loại hoa");

        buttonGroup2.add(typeFlower1KKtxt);
        typeFlower1KKtxt.setText("Hoa đa");
        typeFlower1KKtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFlower1KKtxtActionPerformed(evt);
            }
        });

        jLabel16.setText("Tên hoa");

        jLabel17.setText("Số lượng còn lại");

        buttonGroup2.add(typeFlower2KKtxt);
        typeFlower2KKtxt.setText("Hoa đơn");
        typeFlower2KKtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFlower2KKtxtActionPerformed(evt);
            }
        });

        ResultBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ResultBtn.setText("Kết quả");
        ResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultBtnActionPerformed(evt);
            }
        });

        resetKKBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        resetKKBtn.setText("Reset");
        resetKKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetKKBtnActionPerformed(evt);
            }
        });

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewAndController/Home-icon.png"))); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(ResultBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(home)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(resetKKBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(typeFlower1KKtxt)
                            .addGap(30, 30, 30)
                            .addComponent(typeFlower2KKtxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(codeKKtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(NameKKtxt)
                                .addComponent(AmountKKtxt)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(home)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(codeKKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeFlower1KKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeFlower2KKtxt))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetKKBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameKKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(AmountKKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultBtnActionPerformed
        // TODO add your handling code here:
        String code = codeKKtxt.getText();
        double mark = 0;
        if (typeFlowerKK.equals("Hoa đa")) {
            for (banyanFlower flower : listbanyan) {
                if (code.equals(flower.getCode())) {
                    NameKKtxt.setText(flower.getName());
                    AmountKKtxt.setText(String.valueOf(flower.getAmount()));
                    mark = 1;
                }
            }
            if (mark == 0) {
                NameKKtxt.setText("Không có dữ liệu");
                AmountKKtxt.setText("0.0");
            }
        } else {
            for (singleFlower flower : listsinger) {
                if (code.equals(flower.getCode())) {
                    NameKKtxt.setText(flower.getName());
                    AmountKKtxt.setText(String.valueOf(flower.getAmount()));
                    mark = 1;
                }
            }
            if (mark == 0) {
                NameKKtxt.setText("Không có dữ liệu");
                AmountKKtxt.setText("0.0");
            }
        }
    }//GEN-LAST:event_ResultBtnActionPerformed

    private void typeFlower1KKtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFlower1KKtxtActionPerformed
        // TODO add your handling code here:
        typeFlowerKK = "Hoa đa";
    }//GEN-LAST:event_typeFlower1KKtxtActionPerformed

    private void typeFlower2KKtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFlower2KKtxtActionPerformed
        // TODO add your handling code here:
        typeFlowerKK = "Hoa đơn";
    }//GEN-LAST:event_typeFlower2KKtxtActionPerformed

    private void resetKKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetKKBtnActionPerformed
        // TODO add your handling code here:
        codeKKtxt.setText("");
        buttonGroup2.clearSelection();
        NameKKtxt.setText("");
        AmountKKtxt.setText("");
    }//GEN-LAST:event_resetKKBtnActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        vAdmin = new View_Admin();
        vAdmin.setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountKKtxt;
    private javax.swing.JTextField NameKKtxt;
    private javax.swing.JButton ResultBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField codeKKtxt;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton resetKKBtn;
    private javax.swing.JRadioButton typeFlower1KKtxt;
    private javax.swing.JRadioButton typeFlower2KKtxt;
    // End of variables declaration//GEN-END:variables

}
